### ISSUE TITLE
File HalfDuplexHardwareSerial.h missing

### ISSUE THREAD

**Issue by Laurentdlpr** [HelloSpoon/HelloSpoon-Spark#1]
hello, 
I just brought 2 Xl 320 and I tested your library and so far it is working find to send requests to the servos.
You put an example to recived the data from the servos but the file you use "HalfDuplexHardwareSerial.h" is not included in the github, could you add it  ?

Also I not sure you used the right configuration between the TX and RX pin, did you put a resistor like they use here : http://electronics.stackexchange.com/questions/183410/single-wire-two-way-serial-communication-hardware-configuration

Regards,

**Comment by luisgiii** [comment]
Hi, I guess you're talking about this library:
https://github.com/hackerspace-adelaide/XL320

which is a fork from HelloSpoon-Spark library. For my Spark Core (now Particle) library I'm not using HalfDuplexHardwareSerial.h but you can find this library here: https://github.com/hackerspace-adelaide/HalfDuplexHardwareSerial

At this moment this library (HelloSpoon-Spark) is on hold due to not having access to my Spark Core board, but check the library I shared first in this answer and looks like they have more things solved :-).
